[2025-02-16T15:41:31.634+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: create_iam_role_debug.load_config __airflow_temporary_run_2025-02-16T15:20:05.692287+00:00__ [queued]>
[2025-02-16T15:41:31.643+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: create_iam_role_debug.load_config __airflow_temporary_run_2025-02-16T15:20:05.692287+00:00__ [queued]>
[2025-02-16T15:41:31.644+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2025-02-16T15:41:31.656+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): load_config> on 2025-02-16 00:00:00+00:00
[2025-02-16T15:41:31.663+0000] {standard_task_runner.py:57} INFO - Started process 688 to run task
[2025-02-16T15:41:31.667+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'create_iam_role_debug', 'load_config', '__***_temporary_run_2025-02-16T15:20:05.692287+00:00__', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/AWS_Setup_DAG.py', '--cfg-path', '/tmp/tmp81k4ldj_']
[2025-02-16T15:41:31.669+0000] {standard_task_runner.py:85} INFO - Job 5: Subtask load_config
[2025-02-16T15:41:31.688+0000] {logging_mixin.py:154} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-02-16T15:41:31.716+0000] {task_command.py:416} INFO - Running <TaskInstance: create_iam_role_debug.load_config __airflow_temporary_run_2025-02-16T15:20:05.692287+00:00__ [running]> on host 44e71d63ec52
[2025-02-16T15:41:31.764+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='create_iam_role_debug' AIRFLOW_CTX_TASK_ID='load_config' AIRFLOW_CTX_EXECUTION_DATE='2025-02-16T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='__***_temporary_run_2025-02-16T15:20:05.692287+00:00__'
[2025-02-16T15:41:31.765+0000] {AWS_Setup_DAG.py:29} INFO - File permissions: 644
[2025-02-16T15:41:31.766+0000] {AWS_Setup_DAG.py:34} DEBUG - Config file content length: 391
[2025-02-16T15:41:31.766+0000] {AWS_Setup_DAG.py:50} INFO - Found config sections: ['AWS', 'DWH', 'S3']
[2025-02-16T15:41:31.767+0000] {AWS_Setup_DAG.py:51} INFO - AWS Region: not set
[2025-02-16T15:41:31.773+0000] {python.py:194} INFO - Done. Returned value was: Configuration loaded successfully
[2025-02-16T15:41:31.784+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=create_iam_role_debug, task_id=load_config, execution_date=20250216T000000, start_date=20250216T154131, end_date=20250216T154131
[2025-02-16T15:41:31.809+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-02-16T15:41:31.827+0000] {taskinstance.py:2778} INFO - 1 downstream tasks scheduled from follow-on schedule check
